# Docker Compose for LangChain Pinecone Application

version: '3.8'

services:
  langchain-pinecone-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      # Add your API keys here or use .env file
      - PINECONE_API_KEY=${PINECONE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PINECONE_INDEX_NAME=${PINECONE_INDEX_NAME:-langchain-documents}
    volumes:
      # Mount uploads directory for persistent storage
      - uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

volumes:
  uploads:
